# Dockerfile.dev

FROM node:22.11.0

WORKDIR /usr/src/app

# Copy only package files first for caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your code
COPY . .

# Expose port for NestJS app
ARG APP_PORT
EXPOSE $APP_PORT
