services:
  db:
    image: postgres:17.4
    container_name: postgres_dev
    restart: unless-stopped
    ports:
      - "5401:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Uncomment when restore an sql backup from dump.sql in the root directory
      # - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: >
      sh -c "
        npx wait-on tcp:db:5432 &&
        npm run migration:run &&
        npm run start:dev
      "

volumes:
  postgres_data:
